import MasterCrudGrid from '@/components/grid/MasterCrudGrid';

interface City {
  id?: number;
  name: string;
  state?: string;
  /**
   * Opaque identifier generated by the server.  Not shown/editable in the UI.
   */
  code?: string;
}

export default function CityMaster() {
  return (
    <MasterCrudGrid<City>
      title="City Master"
      endpoint="/api/city/"
      createDraft={() => ({
        name: 'New City',
        state: '',
      })}
      toCreatePayload={(row) => ({
        name: row.name,
        state: row.state || null,
      })}
      toUpdatePayload={(row) => ({
        name: row.name,
        state: row.state || null,
      })}
      columns={[
        { field: 'id', headerName: 'ID', width: 90, editable: false, pinned: 'left' },
        { field: 'name', headerName: 'NAME', width: 220, editable: true },
        { field: 'state', headerName: 'STATE', width: 180, editable: true },
        // `code` is generated on the server; we intentionally hide it from the UI
      ]}
    />
  );
}
