import { formatDisplayDate } from '@/utils/dateFormat';
import type { ReportConfig } from '@/types/reports';

const fmtMoney = (params: { value: unknown }) => Number(params.value || 0).toFixed(2);
const fmtDate = (params: { value: unknown }) =>
  formatDisplayDate((params.value ?? null) as string | Date | null | undefined);

export const REPORT_CONFIGS: ReportConfig[] = [
  {
    id: 'pending-billing',
    label: 'Pending Billing',
    endpoint: 'pending-billing',
    noRowsMessage: 'No pending billing rows.',
    supportsFy: true,
    columns: [
      { field: 'lr_number', headerName: 'LR No', minWidth: 140, flex: 1 },
      { field: 'date', headerName: 'Date', minWidth: 130, flex: 1, valueFormatter: fmtDate },
      { field: 'vehicle_number', headerName: 'Vehicle', minWidth: 140, flex: 1 },
      { field: 'consignor_name', headerName: 'Consignor', minWidth: 180, flex: 1.2 },
      { field: 'consignee_name', headerName: 'Consignee', minWidth: 180, flex: 1.2 },
    ],
  },
  {
    id: 'outstanding-receivables',
    label: 'Outstanding Receivables',
    endpoint: 'outstanding-receivables',
    noRowsMessage: 'No outstanding receivables.',
    supportsFy: true,
    columns: [
      { field: 'client_name', headerName: 'Client', minWidth: 220, flex: 1.4 },
      { field: 'invoice_count', headerName: 'Invoices', minWidth: 120, flex: 1 },
      { field: 'outstanding_total', headerName: 'Outstanding', minWidth: 150, flex: 1, valueFormatter: fmtMoney, cellStyle: { textAlign: 'right' }, currencyTotal: true },
    ],
  },
  {
    id: 'hirememo-register',
    label: 'Hire Memo Register',
    endpoint: 'hirememo-register',
    noRowsMessage: 'No hire memos found.',
    supportsFy: true,
    columns: [
      { field: 'hire_memo_no', headerName: 'HM No', minWidth: 130, flex: 1 },
      { field: 'hire_memo_date', headerName: 'Date', minWidth: 120, flex: 1, valueFormatter: fmtDate },
      { field: 'driver_name', headerName: 'Driver', minWidth: 160, flex: 1.2 },
      { field: 'vehicle_number', headerName: 'Vehicle', minWidth: 140, flex: 1 },
      { field: 'total_amount', headerName: 'Total', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'balance', headerName: 'Balance', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
    ],
  },
  {
    id: 'advance-payment-register',
    label: 'Advance Payment Register',
    endpoint: 'advance-payment-register',
    noRowsMessage: 'No advance payments found.',
    supportsFy: true,
    columns: [
      { field: 'hire_memo_no', headerName: 'HM No', minWidth: 130, flex: 1 },
      { field: 'advance_payment_date', headerName: 'Advance Date', minWidth: 140, flex: 1, valueFormatter: fmtDate },
      { field: 'driver_name', headerName: 'Driver', minWidth: 170, flex: 1.2 },
      { field: 'advance_cash', headerName: 'Advance Cash', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'advance_bank', headerName: 'Advance Bank', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'advance_total', headerName: 'Advance Total', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
    ],
  },
  {
    id: 'driver-settlement',
    label: 'Driver Settlement',
    endpoint: 'driver-settlement',
    noRowsMessage: 'No driver settlement rows.',
    supportsFy: true,
    columns: [
      { field: 'driver_name', headerName: 'Driver', minWidth: 180, flex: 1.3 },
      { field: 'trip_count', headerName: 'Trips', minWidth: 100, flex: 1 },
      { field: 'total_freight', headerName: 'Freight', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'advance_total', headerName: 'Advance', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'balance_due', headerName: 'Balance Due', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
    ],
  },
  {
    id: 'driver-outstanding',
    label: 'Driver Outstanding',
    endpoint: 'driver-outstanding',
    noRowsMessage: 'No driver outstanding rows.',
    supportsFy: true,
    columns: [
      { field: 'driver_name', headerName: 'Driver', minWidth: 200, flex: 1.4 },
      { field: 'trip_count', headerName: 'Trips', minWidth: 100, flex: 1 },
      { field: 'outstanding_amount', headerName: 'Outstanding', minWidth: 140, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
    ],
  },
  {
    id: 'vendor-spend',
    label: 'Vendor Spend',
    endpoint: 'vendor-spend',
    noRowsMessage: 'No vendor spend rows.',
    supportsFy: true,
    columns: [
      { field: 'vendor_name', headerName: 'Vendor', minWidth: 200, flex: 1.4 },
      { field: 'trip_count', headerName: 'Trips', minWidth: 100, flex: 1 },
      { field: 'freight_total', headerName: 'Freight', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'amount_passed_total', headerName: 'Amount Passed', minWidth: 150, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
    ],
  },
  {
    id: 'settlement-variance',
    label: 'Settlement Variance',
    endpoint: 'settlement-variance',
    noRowsMessage: 'No settlement variance rows.',
    supportsFy: true,
    columns: [
      { field: 'financial_year', headerName: 'FY', minWidth: 100, flex: 1 },
      { field: 'invoice_total', headerName: 'Invoice Total', minWidth: 140, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'hirememo_total', headerName: 'HireMemo Total', minWidth: 140, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'variance', headerName: 'Variance', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
    ],
  },
  {
    id: 'advance-aging',
    label: 'Advance Aging',
    endpoint: 'advance-aging',
    noRowsMessage: 'No advance aging rows.',
    supportsFy: true,
    columns: [
      { field: 'hire_memo_no', headerName: 'HM No', minWidth: 130, flex: 1 },
      { field: 'driver_name', headerName: 'Driver', minWidth: 160, flex: 1.2 },
      { field: 'advance_total', headerName: 'Advance', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'balance_due', headerName: 'Balance Due', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'ageing_days', headerName: 'Ageing Days', minWidth: 120, flex: 1 },
      { field: 'bucket', headerName: 'Bucket', minWidth: 100, flex: 1 },
    ],
  },
  {
    id: 'cash-advance-utilization',
    label: 'Cash Advance Utilization',
    endpoint: 'cash-advance-utilization',
    noRowsMessage: 'No utilization rows.',
    supportsFy: false,
    columns: [
      { field: 'financial_year', headerName: 'FY', minWidth: 120, flex: 1 },
      { field: 'cash_advance_total', headerName: 'Cash Advance', minWidth: 150, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'settled_amount', headerName: 'Settled Amount', minWidth: 150, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'utilization_percent', headerName: 'Utilization %', minWidth: 130, flex: 1 },
    ],
  },
  {
    id: 'hirememo-print-trace',
    label: 'Hire Memo Print Trace',
    endpoint: 'hirememo-print-trace',
    noRowsMessage: 'No print trace rows.',
    supportsFy: true,
    serverSearch: true,
    columns: [
      { field: 'hire_memo_no', headerName: 'HM No', minWidth: 130, flex: 1 },
      { field: 'hire_memo_date', headerName: 'Date', minWidth: 120, flex: 1, valueFormatter: fmtDate },
      { field: 'driver_name', headerName: 'Driver', minWidth: 170, flex: 1.2 },
      { field: 'vehicle_number', headerName: 'Vehicle', minWidth: 130, flex: 1 },
      { field: 'print_status', headerName: 'Print Status', minWidth: 130, flex: 1 },
      { field: 'print_count', headerName: 'Print Count', minWidth: 120, flex: 1 },
      { field: 'printed_by', headerName: 'Printed By', minWidth: 140, flex: 1 },
      { field: 'last_printed_at', headerName: 'Last Printed At', minWidth: 160, flex: 1, valueFormatter: fmtDate },
    ],
  },
  {
    id: 'trip-profitability',
    label: 'Trip Profitability',
    endpoint: 'trip-profitability',
    noRowsMessage: 'No profitability rows.',
    supportsFy: true,
    columns: [
      { field: 'invoice_no', headerName: 'Invoice No', minWidth: 120, flex: 1 },
      { field: 'invoice_date', headerName: 'Invoice Date', minWidth: 130, flex: 1, valueFormatter: fmtDate },
      { field: 'lr_number', headerName: 'LR No', minWidth: 130, flex: 1 },
      { field: 'vehicle_number', headerName: 'Vehicle', minWidth: 130, flex: 1 },
      { field: 'revenue', headerName: 'Revenue', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'cost', headerName: 'Cost', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'profit', headerName: 'Profit', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'profit_margin_percent', headerName: 'Margin %', minWidth: 110, flex: 1 },
    ],
  },
  {
    id: 'per-vehicle-cost',
    label: 'Per Vehicle Cost',
    endpoint: 'per-vehicle-cost',
    noRowsMessage: 'No vehicle cost rows.',
    supportsFy: true,
    columns: [
      { field: 'vehicle_number', headerName: 'Vehicle', minWidth: 140, flex: 1.2 },
      { field: 'trip_count', headerName: 'Trips', minWidth: 100, flex: 1 },
      { field: 'total_cost', headerName: 'Total Cost', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'avg_cost', headerName: 'Avg Cost/Trip', minWidth: 130, flex: 1, valueFormatter: fmtMoney },
    ],
  },
  {
    id: 'per-driver-performance',
    label: 'Per Driver Performance',
    endpoint: 'per-driver-performance',
    noRowsMessage: 'No driver performance rows.',
    supportsFy: true,
    columns: [
      { field: 'driver_name', headerName: 'Driver', minWidth: 200, flex: 1.4 },
      { field: 'trip_count', headerName: 'Trips', minWidth: 100, flex: 1 },
      { field: 'revenue', headerName: 'Revenue', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'outstanding', headerName: 'Outstanding', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'collection_efficiency_percent', headerName: 'Collection %', minWidth: 130, flex: 1 },
    ],
  },
  {
    id: 'pod-status-worklist',
    label: 'POD Status Worklist',
    endpoint: 'pod-status-worklist',
    noRowsMessage: 'No POD rows.',
    supportsFy: true,
    columns: [
      { field: 'lr_number', headerName: 'LR No', minWidth: 120, flex: 1 },
      { field: 'date', headerName: 'Date', minWidth: 120, flex: 1, valueFormatter: fmtDate },
      { field: 'vehicle_number', headerName: 'Vehicle', minWidth: 130, flex: 1 },
      { field: 'consignor_name', headerName: 'Consignor', minWidth: 180, flex: 1.2 },
      { field: 'consignee_name', headerName: 'Consignee', minWidth: 180, flex: 1.2 },
      { field: 'pod_received', headerName: 'POD Received', minWidth: 120, flex: 1, valueFormatter: (p) => (p.value ? 'Yes' : 'No') },
      { field: 'pod_verified_at', headerName: 'Verified At', minWidth: 140, flex: 1, valueFormatter: fmtDate },
    ],
  },
  {
    id: 'eway-expiring',
    label: 'E-way Alert',
    endpoint: 'eway-expiring',
    noRowsMessage: 'No e-way alerts.',
    supportsFy: false,
    params: { hours: 8 },
    columns: [
      { field: 'lr_number', headerName: 'LR No', minWidth: 120, flex: 1 },
      { field: 'vehicle_number', headerName: 'Vehicle', minWidth: 130, flex: 1 },
      { field: 'eway_bill_no', headerName: 'E-way Bill', minWidth: 140, flex: 1 },
      { field: 'eway_bill_expiry', headerName: 'Expiry', minWidth: 150, flex: 1, valueFormatter: fmtDate },
      { field: 'hours_remaining', headerName: 'Hours Left', minWidth: 110, flex: 1 },
    ],
  },
  {
    id: 'receivables-aging',
    label: 'Receivables Aging',
    endpoint: 'receivables-aging',
    noRowsMessage: 'No receivables aging rows.',
    supportsFy: true,
    columns: [
      { field: 'invoice_no', headerName: 'Invoice No', minWidth: 120, flex: 1 },
      { field: 'invoice_date', headerName: 'Invoice Date', minWidth: 130, flex: 1, valueFormatter: fmtDate },
      { field: 'client_name', headerName: 'Client', minWidth: 180, flex: 1.2 },
      { field: 'outstanding', headerName: 'Outstanding', minWidth: 130, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'age_days', headerName: 'Age Days', minWidth: 100, flex: 1 },
      { field: 'bucket', headerName: 'Bucket', minWidth: 90, flex: 1 },
    ],
  },
  {
    id: 'audit-log',
    label: 'Audit Log',
    endpoint: 'audit-log',
    noRowsMessage: 'No audit rows.',
    supportsFy: false,
    serverSearch: true,
    params: { limit: 200 },
    columns: [
      { field: 'id', headerName: 'ID', minWidth: 90, flex: 1 },
      { field: 'entity_type', headerName: 'Entity', minWidth: 140, flex: 1 },
      { field: 'entity_id', headerName: 'Entity ID', minWidth: 110, flex: 1 },
      { field: 'action', headerName: 'Action', minWidth: 110, flex: 1 },
      { field: 'user_name', headerName: 'User', minWidth: 140, flex: 1 },
      { field: 'created_at', headerName: 'At', minWidth: 150, flex: 1, valueFormatter: fmtDate },
    ],
  },
  {
    id: 'contract-expiry',
    label: 'Contract Expiry',
    endpoint: 'contract-expiry',
    noRowsMessage: 'No contract expiry rows.',
    supportsFy: false,
    params: { days: 30 },
    columns: [
      { field: 'name', headerName: 'Contract', minWidth: 220, flex: 1.4 },
      { field: 'client_id', headerName: 'Client ID', minWidth: 100, flex: 1 },
      { field: 'end_date', headerName: 'End Date', minWidth: 130, flex: 1, valueFormatter: fmtDate },
      { field: 'days_remaining', headerName: 'Days Remaining', minWidth: 130, flex: 1 },
    ],
  },
  {
    id: 'debit-voucher-register',
    label: 'Debit Voucher Register',
    endpoint: 'debit-voucher-register',
    noRowsMessage: 'No debit vouchers.',
    supportsFy: true,
    columns: [
      { field: 'voucher_id', headerName: 'Voucher ID', minWidth: 100, flex: 1 },
      { field: 'date', headerName: 'Date', minWidth: 120, flex: 1, valueFormatter: fmtDate },
      { field: 'voucher_type', headerName: 'Type', minWidth: 140, flex: 1 },
      { field: 'reference_type', headerName: 'Ref Type', minWidth: 120, flex: 1 },
      { field: 'reference_id', headerName: 'Ref ID', minWidth: 100, flex: 1 },
      { field: 'amount', headerName: 'Amount', minWidth: 120, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'narration', headerName: 'Narration', minWidth: 220, flex: 1.4 },
    ],
  },
  {
    id: 'bank-book',
    label: 'Bank Book',
    endpoint: 'bank-book',
    noRowsMessage: 'No bank book rows.',
    supportsFy: true,
    columns: [
      { field: 'voucher_id', headerName: 'Voucher ID', minWidth: 100, flex: 1 },
      { field: 'date', headerName: 'Date', minWidth: 120, flex: 1, valueFormatter: fmtDate },
      { field: 'voucher_type', headerName: 'Type', minWidth: 140, flex: 1 },
      { field: 'amount', headerName: 'Amount', minWidth: 120, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'narration', headerName: 'Narration', minWidth: 240, flex: 1.5 },
    ],
  },
  {
    id: 'cash-book',
    label: 'Cash Book',
    endpoint: 'cash-book',
    noRowsMessage: 'No cash book rows.',
    supportsFy: true,
    columns: [
      { field: 'voucher_id', headerName: 'Voucher ID', minWidth: 100, flex: 1 },
      { field: 'date', headerName: 'Date', minWidth: 120, flex: 1, valueFormatter: fmtDate },
      { field: 'voucher_type', headerName: 'Type', minWidth: 140, flex: 1 },
      { field: 'amount', headerName: 'Amount', minWidth: 120, flex: 1, valueFormatter: fmtMoney, currencyTotal: true },
      { field: 'narration', headerName: 'Narration', minWidth: 240, flex: 1.5 },
    ],
  },
];
